alter table DDCDI_OPERATION add constraint FK_DDCDI_OPERATION_OPERATION_TYPE foreign key (OPERATION_TYPE_ID) references DDCDI_OPERATION_TYPE(ID);
create index IDX_DDCDI_OPERATION_OPERATION_TYPE on DDCDI_OPERATION (OPERATION_TYPE_ID);
