export enum AttributeMapperMode {
  AUTOMATIC = "AUTOMATIC",
  CUSTOM = "CUSTOM"
}

export enum AttributeType {
  DIRECT_ATTRIBUTE = "DIRECT_ATTRIBUTE",
  ASSOCIATION_ATTRIBUTE = "ASSOCIATION_ATTRIBUTE",
  DYNAMIC_ATTRIBUTE = "DYNAMIC_ATTRIBUTE"
}

export enum ImportExecutionDetailCategory {
  UNIQUE_VIOLATION = "UNIQUE_VIOLATION",
  VALIDATION = "VALIDATION",
  PERSISTENCE = "PERSISTENCE",
  GENERAL = "GENERAL",
  SCRIPTING = "SCRIPTING",
  DATA_BINDING = "DATA_BINDING"
}

export enum ImportTransactionStrategy {
  SINGLE_TRANSACTION = "SINGLE_TRANSACTION",
  TRANSACTION_PER_ENTITY = "TRANSACTION_PER_ENTITY"
}

export enum LogRecordLevel {
  ERROR = "ERROR",
  WARN = "WARN",
  INFO = "INFO",
  DEBUG = "DEBUG"
}

export enum UniquePolicy {
  SKIP = "SKIP",
  UPDATE = "UPDATE",
  ABORT = "ABORT"
}
